### PR TITLE
Fixes "Cannot assign to read only property 'target' of object '#<Event>'"

### PR DESCRIPTION
**Pull request by jelhan**
Details: https://github.com/funkensturm/ember-cli-file-picker/issues/34#issuecomment-268821905

### CODE REVIEW

**Comment by jelhan** [comment]
Removed the files included by accident. Didn't noticed before. Sorry.

**Comment by tniezurawski** [comment]
@jelhan I was looking for that change because my tests are broken after upgrading to the newest `ember-cli` version. With that change it works. Thanks mate!

@fsmanuel Any chance this could be merged and released with new version?

**Comment by fsmanuel** [comment]
@jelhan Thank you! Released as `0.0.12`

**Comment by fsmanuel** [comment]
Sorry for the super late response.

**Pull request merged**
