### PR TITLE
Fixing issue where "filesAreValid" was never called

### LINKED ISSUE #10: `filesAreValid` is not called
If you follow the documentation and extend the component, specifying a `filesAreValid` function, it is never called. After looking into the code, it looks like the issue might be in the `handleFiles` function:

```javascript
if(this.filesAreValid === 'function')
```

The above does not evaluate to true. I think it should be this:

```javascript
if(typeof(this.filesAreValid) === 'function')
```

Am I doing something wrong?

### PR DESCRIPTION
**Pull request by green-arrow**
Resolves #10

### CODE REVIEW

**Comment by green-arrow** [comment]
@fsmanuel I'm not entirely sure why the CI build is failing...any guidance?

**Comment by fsmanuel** [comment]
@green-arrow i'll look into it.

**Comment by fsmanuel** [comment]
@green-arrow i updated master to ember-cli 0.2.7 that should fix the error. can you rebase?

**Comment by green-arrow** [comment]
@fsmanuel Sorry for the delay. I rebased and the CI build is good now :smile:

**Pull request merged**
