### PR TITLE
Fix(Input): Set input to null after select to fix webkit caching

### PR DESCRIPTION
**Pull request by nicford-gojimo**
This fixes the problem of webkit not firing the change event on file selection via system dialog unless the filename changes.

[I have fought long and hard to put tests in place around this, but have finally given up since PhantomJS (I assume?) doesn't allow the filename to be preset. If anyone is able to add a test that proves this functionality, I'd really appreciate seeing how so I'm better armed next time...)

### CODE REVIEW

**Comment by fsmanuel** [comment]
@nicford-gojimo I fixed the tests and updated to ember-cli 2.9.1 can you rebase against master?

**Comment by fsmanuel** [comment]
@nicford-gojimo ping. can you rebase against master?

**Comment by nicford-gojimo** [comment]
Shall do.

-- 

*Nic Ford*

Head of Technology, Gojimo

Gojimo is available on iOS <http://m.onelink.me/44374fef>, Android
<http://m.onelink.me/feee4922> (beta) and web <http://app.gojimo.co/> (beta)

EducationApps Ltd is a registered company in England, No. 07556427

Gojimo, c/o Edspace, Block D Room 203, Hackney Community College, London N1
6HQ

**Comment by fsmanuel** [comment]
@nicford-gojimo thanks!

**Pull request merged**
