### PR TITLE
Update to ember-cli 1.3.8

### PR DESCRIPTION
**Pull request by imanhodjaev**
Updated project to use latest stable ember-cli version.

### CODE REVIEW

**Comment by fsmanuel** [comment]
@imanhodjaev thanks a lot!

**Comment by imanhodjaev** [comment]
@fsmanuel integrations tests on
```
 34.2  Node.js: 0.12  EMBER_TRY_SCENARIO=ember-release  3 min 23 sec
 34.3  Node.js: 0.12  EMBER_TRY_SCENARIO=ember-beta  3 min 11 sec
```

Didn't pass I've been working on it is it ok to merge it into master?

**Comment by imanhodjaev** [comment]
@fsmanuel integrations tests on
```
 34.2  Node.js: 0.12  EMBER_TRY_SCENARIO=ember-release  3 min 23 sec
 34.3  Node.js: 0.12  EMBER_TRY_SCENARIO=ember-beta  3 min 11 sec
```

Didn't pass I've been working on it is it ok to merge it into master?

**Comment by fsmanuel** [comment]
@imanhodjaev I'll look into it.

**Comment by imanhodjaev** [comment]
@fsmanuel thank you very much :smile:

**Comment by fsmanuel** [comment]
@imanhodjaev fixed it.

**Comment by imanhodjaev** [comment]
Yay :+1: cool

**Pull request merged**
